[build]
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/historicweather"
  to = "/.netlify/functions/historicweather/"
  status = 201
  force = true

[[redirects]]
  from = "/weatherforecast"
  to = "/.netlify/functions/weatherforecast/"
  status = 201
  force = true

[[redirects]]
  from = "/backgroundurl"
  to = "/.netlify/functions/backgroundurl/"
  status = 201
  force = true

[[redirects]]
  from = "/geolocation"
  to = "/.netlify/functions/geolocation/"
  status = 201
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=604800"
    access-control-allow-credentials = "true"
    Cross-Origin-Resource-Policy = "cross-origin"
    Referrer-Policy = "origin-when-cross-origin"
