[build]
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "http://localhost:5000/historicweather"
  to = "/.netlify/functions/historicweather/"
  status = 201
  force = true

[[redirects]]
  from = "http://localhost:5000/weatherforecast"
  to = "/.netlify/functions/weatherforecast/"
  status = 201
  force = true

[[redirects]]
  from = "http://localhost:5000/backgroundurl"
  to = "/.netlify/functions/backgroundurl/"
  status = 201
  force = true

[[redirects]]
  from = "http://localhost:5000/geolocation"
  to = "/.netlify/functions/geolocation/"
  status = 201
  force = true
